---
- name: Deploy SPE_miniproject
  hosts: localhost
  tasks:
    - name: Pull latest Docker image
      command: docker pull yourdockerhub/spe_miniproject:latest

    - name: Stop existing container
      command: docker stop spe_miniproject
      ignore_errors: yes

    - name: Remove existing container
      command: docker rm spe_miniproject
      ignore_errors: yes

    - name: Run new container
      command: >
        docker run -d --name spe_miniproject -p 8080:8080 yourdockerhub/spe_miniproject:latest
